### ISSUE TITLE
Pass parameters to ad-hoc job executions

### ISSUE THREAD

**Issue by atomashpolskiy** [bootique/bootique-job#11]
Hi @andrus , may I propose adding an additional version of `com.nhl.bootique.job.scheduler.Scheduler#runOnce` with additional `Map<String, Object>` parameter? This will either override all "default" params, collected from environment and YML config, or - alternatively - will be merged into the default params, preserving params that are absent from the `Map` passed from the caller.

**Comment by andrus** [comment]
+1 Makes sense

**Comment by atomashpolskiy** [comment]
@andrus , which override strategy suits you better? There are +/- for both, but I'd rather simply override everything.

**Comment by andrus** [comment]
I'd say merge is better . We do merge maps in other places.
