### ISSUE TITLE
ListCommand - sort jobs alphabetically

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#35]
When running `-l` in apps with lots of jobs, it is hard to visually locate the job you need. Let's sort the job names alphabetically.

**Comment by andrus** [comment]
@ebondareva : let's make sure we update the BOM to bootique-job:0.15-SNAPSHOT

**Comment by ebondareva** [comment]
@andrus bootique-job version updating is requested in https://github.com/bootique/bootique-bom/pull/1
