### ISSUE TITLE
Use non-zero exit code in ExecCommand, when some of the jobs have failed

### ISSUE THREAD

**Issue by vitalz** [bootique/bootique-job#43]
Simple job has no try-catch block and just throws runtime exception:

```java
public class SomeJob extends BaseJob {

    public SomeJob() {
        super(JobMetadata.build(SomeJob.class));
    }

    private class Task {
    	public void doTask() {
    	    throw new CayenneRuntimeException();
    	}
    }

    @Override
    public JobResult run(Map<String, Object> params) {
        new Task().doTask();
        return JobResult.success(getMetadata());
    }

} 
```

--exec --job some
`[13/Oct/2017:13:42:42,189] main  ERROR i.b.j.c.ExecCommand: Finished job 'some', result: UNKNOWN, message: null`

Then io.bootique.job.command.ExecCommand.run(Cli) handles exception, ignores even JobResult.failure and responses CommandOutcome.succeeded() to the environment, i.e. **0 what is considered as success**. 

For instance, Bamboo logs
`13-Oct-2017 09:42:42 | Finished task 'Run Some Job' with result: Success`

The point is **if runtime exception has occurred then job result will be failure and not equals 0**.

In the situation we use job to build database data and when some data is missing or impacted then deployment process should stop but with 0 the process is still continuing.

**Comment by atomashpolskiy** [comment]
I'd suggest updating the ExecCommand as follows:
1) When there is only one job being run, consider its' result to be the overall command result (i.e. return success or failure code based solely on the job's result)
2) Implement fail-fast behavior in the serial execution mode: terminate execution and return failure immediately, if some of the jobs has failed

Parallel mode (with more than one job) probably deserves some discussion. I think, it's out of discussion, that all jobs should be attempted to execute, but there are still different options, how to handle the results:
1) Always return 0, regardless of specific jobs' results
2) Return failure, if some of the jobs have failed
3) Return failure only if all of the jobs have failed

**Comment by andrus** [comment]
@atomashpolskiy : For serial execution let's implement 1 & 2 the way you described it. It makes sense. For parallel execution I think the second approach is the most appropriate - we should return failure if at least one job is failed.
