### ISSUE TITLE
Integrate "business transaction" ids in job-instrumented

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#48]
A unique ID generator is available in `bootique-metrics` per https://github.com/bootique/bootique-metrics/issues/16 and was already integrated in `jetty-instrumented`. Let's integrate it in `job-instrumented` so that unique tx ids could be printed in the logs for job executions via `%X{txid}`.

**Comment by andrus** [comment]
BTW, there's another thing, which may be outside the scope of the initial implementation - providing TX ids to parallel jobs (e.g. all independent jobs in a "job group" are run in parallel on a thread pool). We may need to think of a solution for this for the future. E.g. storing the TX ID somewhere in the job execution context and passing it down to each child job.

**Comment by ebondareva** [comment]
Note: recording of what has been discussed is here [PR#53](https://github.com/bootique/bootique-job/pull/53).
