### ISSUE TITLE
ConsulLockHandler local job locking

### ISSUE THREAD

**Issue by MegaPapa** [bootique/bootique-job#71]
`ConsulLockHandler` doesn't lock job execution on one runtime, like in `LocalLockHandler`. It's seems like unexpected behavior.
More details in tests: #70

**Comment by atomashpolskiy** [comment]
I can't reproduce the issue. I also verified that a new session is created for each lock handler regardless of whether it shares the same JVM process with other handlers. Session creation is performed once per Bootique runtime (`io.bootique.job.consul.ConsulSession#getOrCreateSession`) and boils down to REST `session/create` call to Consul agent, which fills the node ID parameter in the request and forwards the call to the server [[1]](https://github.com/hashicorp/consul/blob/b5abf61963c7b0bdb674602bfb64051f8e23ddb1/agent/session_endpoint.go#L29). Upon receiving session creation requests Consul server always creates a new session with a random ID [[2]](https://github.com/hashicorp/consul/blob/b5abf61963c7b0bdb674602bfb64051f8e23ddb1/agent/consul/session_endpoint.go#L22). This unique ID is then used by our lock handler to lock a key-value node in Consul (also implemented as a REST call, which ends up in Consul's transactional key-value store [[3]](https://github.com/hashicorp/consul/blob/b5abf61963c7b0bdb674602bfb64051f8e23ddb1/agent/consul/state/txn.go#L42)).

I can't see any reason for the behavior that you observe other than the two jobs being run with a signficant time gap:

```java
scheduler_1.runOnce(new LockJob(), callsCount);
scheduler_2.runOnce(new LockJob(), callsCount);
```

But this is super-strange, given that a thread-pool executor with multiple worker threads is used in your test. Are you sure that you can reproduce the issue?

**Comment by stariy95** [comment]
Test failure (from PR #70) is reproducible on my machine too (MacOS). 
@atomashpolskiy can you please review test itself, is it correct?

Here is log:
```
[main] INFO 🐳 [consul:latest] - Container consul:latest started
[main] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Initializing ExecutorService 
[bootique-job-1] INFO io.bootique.job.consul.lock.ConsulLockHandler - Attempting to lock 'TestJobs/lock'
[bootique-job-2] INFO io.bootique.job.consul.lock.ConsulLockHandler - Attempting to lock 'TestJobs/lock'
[bootique-job-2] ERROR io.bootique.job.consul.lock.ConsulLockHandler - Failed to release lock, manual intervention might be needed: TestJobs/lock
[pool-2-thread-1] INFO org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Shutting down ExecutorService

java.lang.AssertionError: 
Expected :1
Actual   :2
```

**Comment by atomashpolskiy** [comment]
I was not able to find any problems with the test yesterday. I'll take
another look shortly. Btw, I've ran the test on Ubuntu. Will check on my
Mac..

**Comment by stariy95** [comment]
Cool, thanks! Different OS can be the case here (at least Docker can perform differently). 
AFAIK Maxim run tests on Mac too.

**Comment by atomashpolskiy** [comment]
Turns out, I was looking at and talking about `testConsulClusterJobLocking`. Sorry :)

Regarding the `testConsulLocalJobLocking` test: from my point of view this behavior (lock reentrancy, basically) is to be expected. And in any case, why would you ever need two job instances running simultaneously in the same Bootique runtime?

**Comment by atomashpolskiy** [comment]
I guess that the fool-proof solution would be to always decorate serial jobs with an additional local lock :)

**Comment by MegaPapa** [comment]
Suppose, we have api for running job, without local locking we can start several executions of a one job (with one bqruntime).
P.S. bootique-zookeeper has clustered and local locking mechanism.
