### ISSUE TITLE
JobGroup feature doesn't pass incoming parameters to job executions

### ISSUE THREAD

**Issue by dkoyro** [bootique/bootique-job#77]
My code uses `Scheduler.runOnce(String jobName, Map<String, Object> parameters)` API to manage job runs and keep them interacting with the external environment (cancellation, status reporting and etc). 
It works perfectly when it runs a single job - all incoming parameters are being transferred into a running job. 

But it doesn't work for job groups:
I see that `JobGroup` source code doesn't pass Map<String, Object> parameters downstream to a group job executions:

` public JobResult run(Map<String, Object> parameters) {
                traverseExecution(jobExecutions -> {
                    Set<JobResult> results = execute(jobExecutions, jobMap);
                  ...
            }`

**Comment by stariy95** [comment]
Fixed in branches 1.x and master
